name: Simple Hello World

on:
  push:
    branches: [ master ]  # use main if your default branch is main

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, world! My first GitHub Action ran successfully!"
